### ISSUE TITLE
Add a link to GitHub project to the Postmarks UI

### ISSUE THREAD

**Issue by andypiper** [ckolderup/postmarks#131]

**Comment by iambijayd** [comment]
I want to work on this. Can you assign me the issue?

**Comment by ckolderup** [comment]
Sure! Do you have an idea of where it should go? I think the footer is a possibility, but it'll have an RSS feed link down there soon (#98) and it's maybe starting to get kind of crowded down there.

**Comment by iambijayd** [comment]
The RSS feed link and the GitHub link can be placed side by side to the left of the Glitch button.

**Comment by ckolderup** [comment]
@iambijayd I think I prefer the second one, thanks for checking!
