### ISSUE TITLE
Network Feed Styling

### ISSUE THREAD

**Issue by jeffsikes** [ckolderup/postmarks#162]
I did some very minimal work on styling the network feed to improve readability. 

Also, I wanted to make it clearer that there is an option to add a bookmark from a post, which is a great feature!

This uses all the existing color variables, but obviously could cause some styling issues with users that have custom colors configured. Hard to tell as the network feed is behind a login, so I can't really only check my own.

No changes to the templates were made, either.

Will offer up a PR so you can view the changes and attaching a screenshot as well. I'm sure there will be much more extensive styling changes down the line, this is just a refinement.

I thought of making similar changes to the bookmark timeline, but it's fairly readable at the moment and easily style-able. Also more people are customizing that with their own code already.

<img src="https://github.com/ckolderup/postmarks/assets/6627582/f4cc0dbc-1949-4f4f-bfd5-d4a648e4d19e" width="400px"/>

**Comment by ckolderup** [comment]
closed by #163!
