### ISSUE TITLE
Question - what is/was the `seo.json` file for?

### ISSUE THREAD

**Issue by andypiper** [ckolderup/postmarks#179]
There's [this file](https://github.com/ckolderup/postmarks/blob/3a05e6657a3404c4d880ec6c47d9ef11e6974d59/src/seo.json) but I can't seem to find any online references to an seo.json file format or usage - is this a hold-over from something on Glitch? Just curious (and slaying cruft)

**Comment by ckolderup** [comment]
ugh, yeah, that's a bit of metadata that they've split out in a certain mass revision of the glitch starter projects they did a little while before I arrived and was part of the remix I used to start the project. I guess I had just slowly removed all references to it over time but never deleted the file itself!

**Comment by ckolderup** [comment]
I'll remove this real quick, it'll be a good easy way to get my Windows computer set back up with Github SSH keys; I haven't done that since this box imploded a couple months ago.
