### ISSUE TITLE
iOS Shortcut?

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#18]
The bookmarklet technically works on iOS Safari but the ergonomics of setting it up are still annoying and it'd also be cool to be able to submit URLs from inside other apps, which a Shortcut would provide.

**Comment by ckolderup** [comment]
This was actually done by the illustrious @andypiper and I forgot I had logged it here way back last winter! Thank you Andy! https://routinehub.co/shortcut/16547/

**Comment by andypiper** [comment]
Having an API would make this more flexible and as you know the bookmarklet page doesn't close nicely, but this shortcut is a start! We could link to it from the About page and README if you like.

**Comment by ckolderup** [comment]
That seems like a good idea! Once we have the API I definitely think we'll want a page linking to all the different integrations and things people put together. (probably just on the repo wiki for now; I'm not really thinking about full-on documentation just yet)

I'm also thinking I'm going to make a document (blog post?) in the beginning of October summarizing the state of things; I'm hoping to also have a semver/release strategy set up by then.
