### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#20]
I made a very bad logo so that I would be motivated to fix it before too long. Help. The only time I've made a good logo in my life it was by accident and for a joke project among friends.

**Comment by johnholdun** [comment]
does this help

![fedimarks logo](https://user-images.githubusercontent.com/169222/218209733-ad132df9-d1d2-427b-801d-a06c16ac11bb.png)

**Comment by ckolderup** [comment]
it gave me a much-needed laugh, so yes!
