### ISSUE TITLE
Fix layout on mobile

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#4]
It's not great right now, especially on my iPhone mini! We probably need to make the two-column design work more responsively, maybe putting the tags list behind a hamburger menu?

**Comment by HavreLoic** [comment]
Hi @ckolderup is this issue fixed yet?

**Comment by ckolderup** [comment]
@HavreLoic no, it's unlikely that I'll get to styling/display stuff until after the backend & Mastodon integration is better solidified.
