### ISSUE TITLE
revisit outbox generation

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#41]
I think I'm not fully following the spec-- I should be using the notes from the ActivityPub DB, not the bookmark objects. If I swap that over, will that mean that the timeline on Mastodon of a newly-fetched Postmarks instance will be back-populated?

**Comment by silverpill** [comment]
Idk about Mastodon, but the spec requires outbox to contain activities (e.g. `Create(Note)`). I tried to fetch outbox contents from one of postmarks instances and it returned a collection of Note objects.

https://www.w3.org/TR/activitypub/#outbox
