### ISSUE TITLE
Fediverse account name on about page uses @localhost even if domain is set

### ISSUE THREAD

**Issue by benbrown** [ckolderup/postmarks#53]
I updated the src/utils file as described to reflect my personal domain. However, the username on the about page is still @localhost

**Comment by benbrown** [comment]
This is because the values imported from .env are not available in src/utils

**Comment by ckolderup** [comment]
ack, good catch. That should be a quick-ish fix...

**Comment by benbrown** [comment]
yeah i just added the dotenv import and config at the top of that file.
