### ISSUE TITLE
getInboxFromActorProfile fails when remote instance requires HTTP signature on GET

### ISSUE THREAD

**Issue by lmorchard** [ckolderup/postmarks#58]
I tried following my postmarks user from my account [@lmorchard@hackers.town](https://hackers.town/@lmorchard) and got this error in the log on glitch:

![Image](https://github.com/ckolderup/postmarks/assets/21687/14110f66-1d25-4e9e-bdac-9a51bf00b8c3)

The likely culprit is that hackers.town has [`AUTHORIZED_FETCH`](https://docs.joinmastodon.org/admin/config/#authorized_fetch) enabled as a Mastodon setting.

This means that fetching my actor data without HTTP signature headers in the GET request will result in a 401 Unauthorized status.

https://hackers.town/users/lmorchard.json

FWIW, it worked fine from my [@lmorchard@mastodon.social](https://mastodon.social/home) account, where AUTHORIZED_FETCH is not enabled.

**Comment by ckolderup** [comment]
thanks! I was vaguely aware of this setting but didn't have it on my radar.

**Comment by lmorchard** [comment]
It's been a gotcha in a few of my tinkery projects, too! Not sure it's a super-common setting enabled out there, but more of the privacy & security & moderation sensitive instances have switched it on

**Comment by ckolderup** [comment]
@pburke my only hesitation is that the code is such a mess, but if you're willing to help out, I definitely won't turn it down. Up until this point I've been coding in "just get it working" mode so some refactoring is definitely overdue. Thanks!

**Comment by pburke** [comment]
@ckolderup I'll take a crack at it soon and report back!
