### ISSUE TITLE
timezone bug - assumes server time is UTC

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#59]
bookmarks show up as existing in the past on self-hosted instances

**Comment by benbrown** [comment]
This applies to the feed as well. I did some work in my instance to make sure the date is formatted in ISO format so the timezone stuff is respected by consumers.

**Comment by ckolderup** [comment]
@benbrown I just opened #114 -- do you think this approach will cause problems?

**Comment by benbrown** [comment]
@ckolderup Does appending the Z indicate that it is in UTC? I am not that much of an expert alas.

**Comment by benbrown** [comment]
OK I took a look at the PR, yes I think this is good.

**Comment by ckolderup** [comment]
yep, 'Z' is shorthand for +00:00.
