### ISSUE TITLE
set up linting tools + basic github actions checks

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#66]

**Comment by PatOConnor43** [comment]
Hi 👋 

Did you have anything specific in mind? I didn't see any tests yet or formatting/linting.

**Comment by ckolderup** [comment]
@PatOConnor43 for now I'm just thinking some Node 16-compatible version of eslint + prettier with default settings, to cut down on reformatting noise as people (including me, working from different environments that might have different defaults) submit PRs. We do need tests as well-- I've got a separate ticket for that: #21
