### ISSUE TITLE
Make multiple node versions available

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#70]
Node.js 16 is EOL next week, but Glitch won't be able to support newer versions by then. I'd like to keep making the software available on Glitch, but we can specify multiple major versions in the package.json if we just test compatibility.

Once Glitch containers have newer Node.js available we can raise the version floor and also do some refactoring (we won't need the`node-fetch` package anymore, for example)

**Comment by steve-bate** [comment]
FWIW, I've been running [my instance ](https://bookmarks.stevebate.dev) with Node.js 20.x and haven't had problems.

**Comment by ckolderup** [comment]
that's good news! I planned to check this out myself, just looking over any upgrade guides anyone's written for 16->18 and 18->20 since I should still have a good mental model of the codebase before I actually add it to the `engines` list in `package.json`. (still adjusting to not being able to keep half the context for issues in my head)
