### ISSUE TITLE
export to CSV

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#86]
right now we make the SQLite db available for download on the admin page, but a quick export to something friendlier (CSV, JSON, etc) would probably be appreciated. CSV seems most likely to be useful to import into other things, based on experience with bookmarking/read-later/etc services.

UPDATE: re-naming this issue to specifically scope this ticket to CSV, which @PatOConnor43 has made a great start on in #118. I would consider export to other formats in their own tickets with clear naming, details of what the format is, and an explanation for the intended use case if it's not something immediately obvious like another bookmarking service.

**Comment by andypiper** [comment]
*nods* I was thinking the same thing. Mastodon exports e.g. following/follows as CSV, which may be a pattern to use for exporting from the activitypub.db file.
