### ISSUE TITLE
Swap TTF fonts for WOFF2 compressed versions

### ISSUE THREAD

**Issue by boogah** [ckolderup/postmarks#95]
While spinning up a Postmarks site and customizing the CSS, I noticed that the TrueType version of the Public Sans web fonts are being used. I understand that this was likely done because the variable versions are only publicly available for download as TrueType files.

Fortunately, [WOFF2 supports variable fonts](https://henry.codes/writing/how-to-convert-variable-ttf-font-files-to-woff2/) — you just have to compress them using [Google's library](https://github.com/google/woff2).

I did just that and more than halved the file sizes of each:

```
$ woff2_compress PublicSans-Italic-VariableFont_wght.ttf
Processing PublicSans-Italic-VariableFont_wght.ttf => PublicSans-Italic-VariableFont_wght.woff2
Compressed 99991 to 44431.

$ woff2_compress PublicSans-VariableFont_wght.ttf
Processing PublicSans-VariableFont_wght.ttf => PublicSans-VariableFont_wght.woff2
Compressed 95795 to 41419.
```

Allegedly, 95% of folks use browsers that support WOFF2, so [it's safe to use it instead of TTF](https://matthiasott.com/notes/woff-has-left-the-building). If you'd like, I can get a PR in that changes the TTFs over to their WOFF2 counterparts.

**Comment by ckolderup** [comment]
sounds great-- the OFL allows us to do this conversion, right? As long as that's true this sounds like a good move, especially if we're encouraging people to self-host and pay their own bandwidth bills. Would definitely accept a PR!

**Comment by boogah** [comment]
It seems [to be permitted](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&item_id=OFL-FAQ_web#1db14da7) under the OFL, yes. 😅 

I'll _carefully_ convert them, modify the CSS, and the the PR in.
