### ISSUE TITLE
Provide an obvious link to the feed URL

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/postmarks#98]
There's been some mention of this around Mastodon ([example today](https://mastodon.social/@drikkes/111059490937287789)), including at least one person who added a feed URL to the page template themselves-- I had personally assumed that autodiscovery via a `<link rel="alternate" type="application/atom+xml">` in the page head was "enough", but it seems like some tools (IFTTT? wtf?) don't do that kind of lookup resolution. So I guess let's put an RSS icon into the footer of every page that mirrors the href of the link tag.

**Comment by GreenLunar** [comment]
Greetings!

Where is the code that renders the page template?

I'd like to write a patch.

**Comment by ckolderup** [comment]
@GreenLunar thanks! The layout template is located in `src/pages/layouts/main.hbs`.

**Comment by GreenLunar** [comment]
* I'm not familiar with Handlebars, but it reminiscing XSLT and PHP
* What is the filename and filetype of the feed?

If feed is of Atom filetype (application/atom+xml)
If feed is of RSS2 filetype (application/rss+xml)

From observing the file `main.hbs`, I guess the follwing code should do the task.
```diff
    <link rel="apple-touch-icon" sizes="180x180" href="https://cdn.glitch.global/8eaf209c-2fa9-4353-9b99-e8d8f3a5f8d4/postmarks-touch-icon-180.png?v=1693611327251" />
    <link rel="shortcut icon" href="https://cdn.glitch.global/8eaf209c-2fa9-4353-9b99-e8d8f3a5f8d4/postmarks-favicon.ico?v=1693611323474" />
    <link rel="stylesheet" href="/style.css" />
+   <link rel="alternate" type="application/atom+xml" title="Follow via RSS: {{title}} | {{siteName}}" href="{{{feedLink}}}"/>
```

**Comment by GreenLunar** [comment]
> So I guess let's put an RSS icon into the footer of every page that mirrors the href of the link tag.

Is there a follow button?

I suggest to add the RSS near or incorporate it with the Follow button instead of placing it as a formal symbol at the bottom of the page.

>  I had personally assumed that autodiscovery via a <link rel="alternate" type="application/atom+xml"> in the page head was "enough", but it seems like some tools (IFTTT? wtf?) don't do that kind of lookup resolution.

You have assumed correctly.

May you please refer me to an IFTTT tool of sort?

**Comment by GreenLunar** [comment]
Is any of these good?

PNG (Public Domain)
https://www.iconsdb.com/white-icons/rss-icon.html

SVG (Public Domain)
https://thenounproject.com/icon/rss-201312/

SVG (Public Domain)
https://thenounproject.com/icon/rss-14199/

SVG (Public Domain)
https://wikiless.tiekoetter.com/wiki/File:RSS_icon.svg?lang=en

PNG (Public Domain)
https://wikiless.tiekoetter.com/wiki/File:Rss_icon.png?lang=en

CSS (Kevin Huff)
https://css-tricks.com/the-shapes-of-css/#aa-rss-feed-shape-via-kevin-huff

SVG (MPL)
https://wikiless.tiekoetter.com/wiki/File:Feed-icon.svg?lang=en

We can make one of our own.

**Comment by GreenLunar** [comment]
@iambijayd do you want to work on this too?

**Comment by ckolderup** [comment]
SVG (Public Domain)
https://thenounproject.com/icon/rss-201312/

I like this one!

**Comment by iambijayd** [comment]
> @iambijayd do you want to work on this too?
@GreenLunar Yeah, sure. Will make a PR that can add a RSS as well as github icon

**Comment by GreenLunar** [comment]
May someone please send a link to an updated instance where the results
of this commit can be seen?

**Comment by ckolderup** [comment]
@GreenLunar I updated https://postmarks.glitch.me to show the new footer.

**Comment by GreenLunar** [comment]
Beautifully done!

I think of a couple of kind of graphics.

For wider display: [ICON] + RSS or RSS + [ICON]

For narrower display: [ICON] (just like it is now)

This is in order to raise awareness amongst new netizens (usually
teenagers) as web browser vendors don't do so anymore.

Thank you!
